### ISSUE TITLE
Formatting on save puts cursor on top of file

### ISSUE THREAD

**Issue by carleryd** [humio/atom-elm-format#1]
This plugin is blazingly fast compared to using Atom Beautify, however it's really annoying that the cursor jumps to the top of the screen. Any idea why this happens? It's doesn't always happen, but most times it does. I'm using format on save.

**Comment by benjick** [comment]
Yeah I've seen it to and it sadly defeats the purpose of the plugin. I've looked into somehow saving the cursor position and restoring it, but I haven't found a good way yet.

I'll keep you posted!

**Comment by note89** [comment]
Also if you keep ctrl+s pressed down all code gets deleted or atom crashes on some computers. A denounce is maybe a solution for it.

**Comment by benjick** [comment]
Thanks @note89, I'll implement that as well

**Comment by avh4** [comment]
@benjick in most cases, just restoring the cursor index into the file will get the cursor close enough, and will be at least always better than the current behavior.  Here's a similar fix for the jsformat-atom plugin: https://github.com/jdc0589/jsformat-atom/pull/9/files

**Comment by benjick** [comment]
@avh4 Thanks, I've implemented this now, but it's not as good as I would want it to be, but yeah, 100x better than before. The problem I have now is that the line your were on get's pushed down towards the bottom of your screen.

**Comment by benjick** [comment]
@note89 @carleryd Both your issues should be somewhat resolved with 1.0.0 so I'm closing this now

Thanks for the help @avh4!
