### ISSUE TITLE
Default to format on save

### ISSUE THREAD

**Issue by rtfeldman** [humio/atom-elm-format#10]
Great plugin! I just switched from Sublime to Atom, and totally thought this wasn't working - I expected it to format on save by default (like it does in Sublime, which I think is the correct default since that's the most common way people use it) and was really surprised when I figured out it was disabled by default.

Can we enable this by default so others don't run into that? I think especially people coming from Sublime will think this isn't working, whereas if you don't want it, it's easy to disable. 😄 

Thanks for the great work!

**Comment by benjick** [comment]
Hey

I just published 2.0.0 with has this enabled by default

**Comment by rtfeldman** [comment]
Awesome, thanks!
