### ISSUE TITLE
Elm blocks not formatted by `elm-format`

### ISSUE THREAD

**Issue by OvermindDL1** [humio/atom-elm-format#13]
Elm blocks not formatted by `elm-format`, such as a GLSL block of:

``` elm
fragmentShader : Shader {} Uniform Varying
fragmentShader =
    [glsl|
         precision mediump float;
         varying vec4 fragColor;

         void main () {
             gl_FragColor = fragColor;
         }
    |]
```

Any chance on custom formatting for a few popular block types, like glsl (could defer to other Atom formatters for a given unknown name)?

See https://groups.google.com/forum/#!topic/elm-discuss/HIdcbC0IOHk for reference.

**Comment by benjick** [comment]
I think you want to open an issue here: https://github.com/avh4/elm-format

This is just the atom extension using that binary

**Comment by OvermindDL1** [comment]
Correct, just wanting atom support for this.  elm-format is not wanting to touch other arbitrary embedded languages and as such it does not and will not touch them.

**Comment by benjick** [comment]
I'm not sure, this extension does no analysis of the code, it just ships the whole thing to `elm-format`, picks up the output and replaces the current editor content.

**Comment by OvermindDL1** [comment]
Hmm, perhaps better for language-elm in that case...

**Comment by benjick** [comment]
I'm closing this because it's not really in the scope of this project
