### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BryanJBryce** [humio/atom-elm-format#15]
Every time I save all I get is a notification banner showing:

> elm-format exited with code null

**Comment by BryanJBryce** [comment]
Ah, gotta install elm-format...

**Comment by leggsimon** [comment]
@BryanJBryce I'm getting this error, I've install `elm-format` but if I run in the command line I'm prompted with a (`y/n`) whether I want to override the file which is what I guess is what's causing the null error. How did you manage to fix it?

**Comment by despairblue** [comment]
@leggsimon this plugin expects an absolute path to be configured in the settings. It defaults to `/usr/local/bin/elm-format`.

I think it may be better to use `$PATH` for that.
