### ISSUE TITLE
elm-format exited with code null

### ISSUE THREAD

**Issue by ghost** [humio/atom-elm-format#18]
atom version 1.12.2
elm-format apm 2.1.0
elm-format exited with code null, does not format code in the editor.

Worked about a month ago. My hard drive had died. Setting things backup does not seem to work now.

**Comment by vladknp** [comment]
Same problem

**Comment by benjick** [comment]
Hey, this error is shown when the plugin can't find the binary (I've added an error message for this in future versions). Can you check if you have installed the elm-format binary and that the plugin has the right path for it?

**Comment by ghost** [comment]
I have /home/sotrhraven/bin/elm-format
now getting exited with code 1. Still no formatting of text.

**Comment by mltsy** [comment]
I had the same issue (`exited with code null`), then I realized 2 things:

1. This package requires the [native executable, elm-format](https://github.com/avh4/elm-format) to be installed, and I didn't have it, so I installed that.
    - Now I was getting `code 1` instead of `code null`
2. My code had an error in it, which I identified using the [linter-elm-make](https://atom.io/packages/linter-elm-make) package.
   - After I fixed that... it worked!

**Comment by m0nq** [comment]
I tried mltsy's solution, and am still having the same problem. :/

**Comment by nilsmagnus** [comment]
I got the same error on ubuntu and solved it by creating a symlink.

The plugin expects the elm-format to be located in 
    
      /usr/local/bin/elm-format

So in linux, you could add a symlink to please the plugin:

    sudo ln -s /usr/bin/elm-format /usr/local/bin/elm-format

**Comment by AionDev** [comment]
for **windows** people still struggling with this: 
👉 step1: `apm install elm-format`
👉 step2: then make sure you have `Elm Platform` installed from [here](https://github.com/elm-lang/elm-platform).
👉 step3: make sure you unzipped the `elm-format` **executable**[ from here ](https://github.com/avh4/elm-format/releases/tag/0.7.0-exp) - and place it inside the same folder as the **Elm Platform installation** - you can see it in the path below.
👉 step4: include `C:/Program Files (x86)/Elm Platform/0.18/bin/elm-format.exe` path in the box of elm-format package - inside the Atom UI - Settings tab as you can see below.

![atom error elm-format exited with code null - how to fix this error in windows 10](https://cloud.githubusercontent.com/assets/20288140/26254054/f634c298-3cbd-11e7-919e-b76436bde606.png)

**Comment by benjick** [comment]
Hey. In 2.2.0 we're just defaulting to `elm-format` in your path courtesy of @MazeChaZer. Can someone try it out?

**Comment by mltsy** [comment]
WFM! :100:
I updated, checked the settings to make sure there was nothing in the elm-format path, and formatted a file just fine :smile:

**OS:** Ubuntu 16.04
**Atom:** 1.13.1
**which elm-format:** /usr/local/bin/elm-format
