### ISSUE TITLE
With format-on-save, the buffer is temporarily cleared, messing up Undo

### ISSUE THREAD

**Issue by avh4** [humio/atom-elm-format#4]
To reproduce:
- Enable format on save
- Edit an Elm file
- Save (causing a format)
- Press Cmd-Z to undo

The entire contents of the file will be empty.  You have to press Cmd-Z a second time to get the previous (unformatted) file back.

**Comment by benjick** [comment]
Even on 1.2.0?

**Comment by avh4** [comment]
Nope, fixed in 1.2.0.
