### ISSUE TITLE
Implement --elm-version

### ISSUE THREAD

**Issue by benjick** [humio/atom-elm-format#9]
Something like

```
version: {
  type: ['boolean', 'integer'],
  "default": false,
  "enum": [false, 16, 17]
}
```

**Comment by anagrius** [comment]
null probably better than false

**Comment by ItamarGronich** [comment]
So, no way to enforce an elm version? i'm using elm 16 and getting incompatible format errors.

**Comment by benjick** [comment]
Not really, but you can download the corresponding binary from https://github.com/avh4/elm-format/releases

**Comment by anagrius** [comment]
Reopen if still wanted
